// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("Bookmark")]
public partial class Bookmark
{
    [Key]
    public int BookmarkID { get; set; }

    public Guid? UserID { get; set; }

    public int? NovelID { get; set; }

    public int? ChapterID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("NovelID")]
    [InverseProperty("Bookmarks")]
    public virtual Novel Novel { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Bookmarks")]
    public virtual User User { get; set; }
}