// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("Card")]
public partial class Card
{
    [Key]
    public int CardID { get; set; }

    public Guid UserID { get; set; }

    [Required]
    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [Required]
    [StringLength(19)]
    public string CardNumber { get; set; }

    [Required]
    [StringLength(100)]
    public string CardHolderName { get; set; }

    [Required]
    [StringLength(5)]
    public string ExpirationDate { get; set; }

    [Required]
    [StringLength(4)]
    public string CVV { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [InverseProperty("Card")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    [ForeignKey("UserID")]
    [InverseProperty("Cards")]
    public virtual User User { get; set; }
}