// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("Chapter")]
public partial class Chapter
{
    [Key]
    public int ChapterID { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [Required]
    public string Content { get; set; }

    public int ChapterNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PublishDate { get; set; }

    public int? NovelID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [InverseProperty("Chapter")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("NovelID")]
    [InverseProperty("Chapters")]
    public virtual Novel Novel { get; set; }
}