// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("Comment")]
public partial class Comment
{
    [Key]
    public int CommentID { get; set; }

    [Required]
    public string Content { get; set; }

    public Guid? UserID { get; set; }

    public int? NovelID { get; set; }

    public int? ChapterID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedDate { get; set; }

    [ForeignKey("ChapterID")]
    [InverseProperty("Comments")]
    public virtual Chapter Chapter { get; set; }

    [ForeignKey("NovelID")]
    [InverseProperty("Comments")]
    public virtual Novel Novel { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Comments")]
    public virtual User User { get; set; }
}