// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("Novel")]
public partial class Novel
{
    [Key]
    public int NovelID { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    [Column(TypeName = "ntext")]
    public string OtherName { get; set; }

    public int? TotalPages { get; set; }

    [Column(TypeName = "ntext")]
    public string CoverImage { get; set; }

    public int ViewCount { get; set; }

    public int FavoriteCount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PublishedDate { get; set; }

    public Guid? PublisherID { get; set; }

    public int? Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedDate { get; set; }

    [InverseProperty("Novel")]
    public virtual ICollection<Bookmark> Bookmarks { get; set; } = new List<Bookmark>();

    [InverseProperty("Novel")]
    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();

    [InverseProperty("Novel")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("Novel")]
    public virtual ICollection<NovelGenre> NovelGenres { get; set; } = new List<NovelGenre>();

    [ForeignKey("PublisherID")]
    [InverseProperty("Novels")]
    public virtual User Publisher { get; set; }

    [InverseProperty("Novel")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();
}