// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("NovelGenre")]
public partial class NovelGenre
{
    public int? NovelID { get; set; }

    public int? GenreID { get; set; }

    [Key]
    public int NovelGenreID { get; set; }

    [ForeignKey("GenreID")]
    [InverseProperty("NovelGenres")]
    public virtual Genre Genre { get; set; }

    [ForeignKey("NovelID")]
    [InverseProperty("NovelGenres")]
    public virtual Novel Novel { get; set; }
}