// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("Role")]
public partial class Role
{
    [Key]
    public int RoleID { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    public int RoleCode { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RolesMenu> RolesMenus { get; set; } = new List<RolesMenu>();

    [InverseProperty("Role")]
    public virtual ICollection<RolesPermission> RolesPermissions { get; set; } = new List<RolesPermission>();

    [InverseProperty("Role")]
    public virtual ICollection<UsersRole> UsersRoles { get; set; } = new List<UsersRole>();
}