// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

[Table("User")]
public partial class User
{
    [Key]
    public Guid UserID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RegistrationDate { get; set; }

    [Required]
    [Unicode(false)]
    public string Avatar { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string UserCode { get; set; }

    [StringLength(10)]
    public string Gender { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Provider { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastLoggedIn { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Bookmark> Bookmarks { get; set; } = new List<Bookmark>();

    [InverseProperty("User")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("Publisher")]
    public virtual ICollection<Novel> Novels { get; set; } = new List<Novel>();

    [InverseProperty("User")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    [InverseProperty("User")]
    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();

    [InverseProperty("User")]
    public virtual ICollection<UsersRole> UsersRoles { get; set; } = new List<UsersRole>();
}