// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraNovel.Domain.Models;

public partial class UsersRole
{
    [Key]
    public int UsersRolesID { get; set; }

    public Guid? UserID { get; set; }

    public int? RoleID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("UsersRoles")]
    public virtual Role Role { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UsersRoles")]
    public virtual User User { get; set; }
}